steps:
  #Docker build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/project-name'
      - '.'
  # Push container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/project-name'
 
  # Deploy container image to Cloud Run project-name
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'project-name',
        '--image',
        'gcr.io/$PROJECT_ID/project-name',
        '--region',
        'asia-southeast1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--min-instances',
        '1',
      ]
images:
  - 'gcr.io/$PROJECT_ID/project-name'