version: '3.8'
services:
  database:
    image: postgres:13.5
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-myuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mypassword}
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  database: